rsvplist.settings:
  type: config_object
  label: 'RSVP List Content Types Settings'
  mapping:
    allowed_types:
      type: sequence
      label: 'Content Types RSVP Form can display on'
      sequence:
        type: string 
        label: 'Content type'